Web/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

app/models.py
from django.db import models
import datetime
from django.utils import timezone
from django.contrib.auth.models import AbstractUser, AbstractBaseUser, BaseUserManager
from django.conf import settings



class AccountManager(BaseUserManager):
    def create_user(self, email, username, password=None):
        if not email:
            raise ValueError("Please enter email address")
        if not username:
            raise ValueError("Please enter username")
        user = self.model(
            email=self.normalize_email(email)
        )
        user.set_password(password)
        user.save(using=self._db)
        return user
        
    def create_superuser(self,email,username,password):
        user = self.create_user(
                email=self.normalize_email(email),
                password = password,
                username = username,
             )
        user.is_admin = True
        user.is_staff = True
        user.is_superuser = True
        user.save(using=self._db)
        return user


class Account(AbstractBaseUser):
    email = models.EmailField(verbose_name="email", unique=True)
    username = models.CharField(verbose_name="username", max_length=30)
    firstname = models.CharField(verbose_name="firstname", max_length=30)
    lastname = models.CharField(verbose_name="lastname", max_length=30)
    date_joined = models.DateTimeField(verbose_name="joindate", auto_now_add=True)
    last_login = models.DateTimeField(verbose_name="logindate", auto_now=True)
    is_active = models.BooleanField(default=True)
    is_admin = models.BooleanField(default=False)
    is_staff = models.BooleanField(default=False)
    is_superuser = models.BooleanField(default=False)
    is_doctor = models.BooleanField('doctor status', default=False)
    is_patient = models.BooleanField('patient status', default=False)
    birthday = models.DateField(auto_now=False, null=True, blank=True)
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username',]

    objects = AccountManager()

    def __str__(self):
        return self.email
    def has_perm(self, perm, obj=None):
        return self.is_admin
    def has_module_perms(self, app_label):
        return True


class DoctorDepartment(models.Model):
    USER_CLINIC_CHOICES = (
        ("1", 'Neurology'),
        ("2",'Ear, Nose and Throat Disorders'),
        ("3", 'Diet and Nutrition'),
        ("4", 'Cardiology'),
        ("5", 'Psychology'),
    )
    user = models.OneToOneField(settings.AUTH_USER_MODEL,on_delete=models.CASCADE, blank=True, null=True)
    department = models.CharField(choices=USER_CLINIC_CHOICES, max_length=100)
    

class Appointment(models.Model):
    old = models.BooleanField(default=False)
    user = models.ForeignKey(settings.AUTH_USER_MODEL,blank=True, null=True,on_delete=models.DO_NOTHING)
    date = models.DateField(auto_now=False, null=True, blank=True)
    time_start = models.TimeField(('start time'), blank=True, null=True)
    time_end =models.TimeField(('end time'), blank=True, null=True)
    appointment_with = models.ForeignKey(DoctorDepartment, on_delete=models.CASCADE)
    app_rate = models.IntegerField(default = 0)

class RateModel(models.Model):
    doctor = models.ForeignKey(DoctorDepartment, on_delete=models.CASCADE)
    rate = models.IntegerField(blank=True, default = 0)
    av_rate = models.IntegerField(blank=True, default = 0)

app/templates/app/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8" name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}Appointment System{% endblock %} </title>

    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <style>
        body {
            background-image: url("https://1m44371baa141ch1f82vaqdq-wpengine.netdna-ssl.com/wp-content/uploads/2017/01/Dollarphotoclub_68339986.jpg");
            height: 10%;
            background-position: below;
            background-repeat: no-repeat;
            background-size: cover;
            }
    </style>
</head>

<body>
    <div class="body"></div>
    {% include "app/header.html" %}

    {% block body %}

    {% endblock %}
    <script src="{% static "js/jquery.min.js" %}"></script>
    <script src="{% static "js/bootstrap.min.js" %}"></script>

</body>
</html>

app/templates/app/blog.html
{% extends 'app/base.html' %}


{% block body%}
<style>
    h1{
        color:Black;
        text-align: center;
    }
    h4{
        color:black;
    }
    body{
        background-image: url("https://cdn7.dissolve.com/p/D2115_158_005/D2115_158_005_1200.jpg")
    }
</style>

<div style="text-align: center;">
<h1>Today's Videos</h1><br>
<h4>Solutions for reflux</h4>
<iframe width="560" height="315" src="https://www.youtube.com/embed/DQew7AiwPWw" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
</div>
{% endblock %}

app/templates/app/contactpage.html
{% extends 'app/base.html' %}

{% block body %}
<style>

.fa {
  padding: 20px;
  font-size: 30px;
  width: 50px;
  text-align: center;
  text-decoration: none;
  margin: 5px 2px;
}

.fa:hover {
    opacity: 0.7;
}

</style>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<div class="container-fluid">
<div class="row">
    <div class="col-sm-1"></div>
    <div class="col-sm-6">
<br><br>
<div class="mapouter"><div class="gmap_canvas"><iframe width="524" height="500" id="gmap_canvas" src="https://maps.google.com/maps?q=MEF%20%C3%9Cniversitesi&t=&z=13&ie=UTF8&iwloc=&output=embed" frameborder="0" scrolling="no" marginheight="0" marginwidth="0"></iframe><a href="https://periodic-table-of-elements.net"></a></div><style>.mapouter{position:relative;text-align:right;height:500px;width:524px;}.gmap_canvas {overflow:hidden;background:none!important;height:500px;width:524px;}</style></div>
</div>
<div class="col-sm-3">
    <br><br>
    <p style="background-color:white; font-family: monospace; font-size: xx-large;">Contact Us!</p>
    <br>
    <p style="background-color:white; font-family: monospace; font-size: large;">E-mail: akarcaym@mef.edu.tr</p>
    <p style="background-color:white;font-family: monospace; font-size: large;">Phone: 05327487670</p>
    <p style="background-color:white; font-family: monospace; font-size: large;">E-mail: cercioglug@mef.edu.tr</p>
    <p style="background-color:white;font-family: monospace; font-size: large;">Phone: 053963971414</p>
    <p style="background-color:white; font-family: monospace; font-size: large;">E-mail: gulteny@mef.edu.tr</p>
    <p style="background-color:white;font-family: monospace; font-size: large;">Phone: 05342975871</p>
    &nbsp;&nbsp;&nbsp;<a href="https://www.youtube.com/user/akarcaym" style="background-color:white;color:red" class="fa fa-youtube"></a>
    &nbsp;&nbsp;&nbsp;<a href="https://twitter.com/akarcaym"style="background-color:white" class="fa fa-twitter"></a>

</div> </div></div>   {% endblock %}

app/templates/app/dept_select.html
{% extends 'app/base.html' %}


{% block body%}


<style>
body{
  background-image: url("https://emerging-europe.com/wp-content/uploads/2018/01/bigstock-Male-Doctor-In-The-Hospital-190586731.jpg");
  }
h4{
    color:Maroon;
       }
ul {
  color:black;
  margin: 0;
  padding: 0;
}

li {
    color: black;
    float: up;
    margin: 10px;
}
a{
    color: #660033;
}

.button1 {
    color: black !important;
    text-transform: uppercase;
    text-decoration: none;
    padding: 0px;
    display: inline-block;
    border: none;
    transition: all 0.4s ease 0s;
}

.button1:hover {
    text-shadow: 0px 0px 6px rgba(255, 255, 255, 1);
    -webkit-box-shadow: 0px 5px 40px -10px rgba(0,0,0,0.57);
    -moz-box-shadow: 0px 5px 40px -10px rgba(0,0,0,0.57);
    transition: all 0.4s ease 0s
}
</style>
<center><font size="5"><a href="/doctorlist/1/">Neurology</a></font><br>
<center><font size="5"><a href="/doctorlist/2/">Ear, Nose and Throat Disorders</a></font><br>
<center><font size="5"><a href="/doctorlist/3/">Diet and Nutrition</a></font><br>
<center><font size="5"><a href="/doctorlist/4/">Cardiology</a></font><br>
<center><font size="5"><a href="/doctorlist/5/">Psychology</a></font><br>
<h4>If You Have Any of These, Choose: Cardiology</h4>
<ul>
  <li>Difficulty in breathing</li>
  <li>Weakness</li>
  <li>Tingle on the left arm</li>
</ul>
<h4>If You Have Any of These, Choose: Neurology</h4>
<ul>
  <li>Headache</li>
  <li>Dizziness</li>
  <li>Loss of balance</li>
</ul>

{% endblock %}

app/templates/app/doctorappointment.html
{% extends 'app/base.html' %}


{% block body%}
<style>
    body{
        background-image: url("https://www.esmsolutions.com/wp-content/uploads/2018/02/appointment-background.jpg")
    }
    p{
        color:red
    }
    h1{
        color:yellow;
        text-align:center
    }
    a{
        color: white;
        text-align: center;
    }

</style>
<h1>Patient Appointments</h1><br>
<p>{{err_msg}}</p>
{% for item in data%}
Patient :<a>{{item.user.firstname}} {{item.user.lastname}} | Birthday : {{item.user.birthday}} </a><br>
Date : <a>{{item.date}} Time : {{item.time_start}} - {{item.time_end}} </a><br>
<hr>

{% endfor %}
{% endblock %}

app/templates/app/doctorlist.html
{% extends 'app/base.html' %}


{% block body%}


<style>
body{
    background-image: url("https://region51.com/images/news/bd46b024945c70514ba183c6a4639492_middle.jpg");
    }

p{
  color: white;
}

.button1 {
    color: #fff !important;
    text-transform: uppercase;
    text-decoration: none;
   
    padding: 0px;
    border-radius: 50px;
    display: inline-block;
    border: none;
    transition: all 0.4s ease 0s;
}

.button1:hover {
    text-shadow: 0px 0px 6px rgba(255, 255, 255, 1);
    -webkit-box-shadow: 0px 5px 40px -10px rgba(0,0,0,0.57);
    -moz-box-shadow: 0px 5px 40px -10px rgba(0,0,0,0.57);
    transition: all 0.4s ease 0s
}
</style>
{% for item in doctor%}
<div class="button_cont" ><a href="/schedule/{{ item.user.username}}/" style="font-size:30px; color:white" class=" button button1 ">{{item.user.firstname}} {{item.user.lastname}}</a></div><br>



{% endfor %}
{% endblock %}

app/templates/app/header.html
  <div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom box-shadow">
    <h5 class="my-0 mr-md-auto font-weight-normal">Appointment System</h5>
    <nav class="my-2 my-md-0 mr-md-3"></nav>
      {% if request.user.is_authenticated  %}
      {% if user.is_patient %}

      
      <a class="p-2 text-dark" href="/getappointment">Get Appointment</a>
    <a class="p-2 text-dark" href="/appointment/">My Appointments</a>
    <a class="p-2 text-dark" href="/blog/">Blog</a>
       <a class="p-2 text-dark" href="{% url 'logout' %}">Logout</a>
    </nav>
    {% else%}
    <a class="p-2 text-dark" href=""></a>
    
    <a class="p-2 text-dark" href="/getappointment"></a>
  <a class="p-2 text-dark" href="/doctorappointment/">My Appointments</a>

     <a class="p-2 text-dark" href="{% url 'logout' %}">Logout</a>
  </nav>
    {% endif %}
    {% else %}
    <a class="p-2 text-dark" href="/whoarewe/">Information</a>
    <a class="p-2 text-dark" href="/contact/">Contact</a>
    <a class="p-2 text-dark" href="/register/">Register</a>
    <a class="btn btn-outline-primary" href="{% url 'login' %}">Login</a></a>
    {% endif %}
  </div>

  

app/templates/app/homepage.html
{% extends 'app/base.html' %}


{% block body%}
<style>
    h1{
        text-align: center;
        color: Maroon;
    }
    body{
        background-image: url("http://akspabrodedantel.com/wp-content/uploads/2018/02/arkaplan-2-1-frozen.jpg");
    }
</style>
<br><br><br><br><br><br><br><br><h1>Welcome to Appointment System</h1>
{% endblock %}

app/templates/app/login.html
{% extends 'app/base.html'%}
{% block body %}
<style type="text/css">
.form-signin {
  width: 100%;
  max-width: 330px;
  padding: 15px;
  margin: 0 auto;
}
.form-signin .checkbox {
  font-weight: 400;
}
.form-signin .form-control {
  position: relative;
  box-sizing: border-box;
  height: auto;
  padding: 10px;
  font-size: 16px;
}
.form-signin .form-control:focus {
  z-index: 2;
}
.form-signin input[type="email"] {
  margin-bottom: -1px;
  border-bottom-right-radius: 0;
  border-bottom-left-radius: 0;
}
.form-signin input[type="password"] {
  margin-bottom: 10px;
  border-top-left-radius: 0;
  border-top-right-radius: 0;
}

</style>


<form method="post" class="form-signin">
    {% csrf_token%}
    <h1 class="h3 mb-3 font-weight-normal">Login</h1>
      
        
                 
        <input type="email" name="email" id="inputEmail" class="form-control" placeholder="Email address" required autofocus>
        
        <input type="password" name="password" id="inputPassword" class="form-control" placeholder="Password" required>
        {% for field in login_form %}
        <p>   
            {% for error in login_form.field.errors %}
            <p style="color:red;">{{error}}</p>
                {% endfor %}
            </p> 
            {% endfor %}
            {% if login_form.non_field_errors %}
            <div style="background-color:red ;color:white">
            <p>{{login_form.non_field_errors}}</p>
            </div>
        {% endif %}
    <button class="btn btn-lg btn-primary btn-block" type="submit">Login</button>
</form>


{% endblock %}

app/templates/app/myappointments.html
{% extends 'app/base.html' %}


{% block body%}
<style>
    body{
        background-image: url("https://www.esmsolutions.com/wp-content/uploads/2018/02/appointment-background.jpg")
        }
    
    z{
        bottom :500;
        text-align: center;
        border-style: solid;
        border-radius: 60px;
        border-color: #e60000;
        
    }
    
    i{
    color:white;
    }
</style>
<h1 class="lead" style="text-align: center; color:yellow">Your Appointments </h1>
<div style=" text-align: center; ">
    <i>   

<z><b>Please be there 15 minutes ago</b></z><br>
{% for item in data%}{% csrf_token %}
    {% if item.old == False %}
    <b>Doctor name : </b>{{item.appointment_with.user.firstname}} {{item.appointment_with.user.lastname}} <b>Department : </b>{{item.appointment_with.get_department_display}} <br>
    <b> Date :</b> {{item.date}} <b>Time :</b> {{item.time_start}} - {{item.time_end}} <button><a href="/delete/{{item.id}}/">Cancel</button></a><br>
    
    {% endif %}
{% endfor %}

<hr></i>
<p class="lead" style="color:yellow;">Past Appointments </p>


{% for item in data%}
{% if item.old == True %}

<div style="color:gray;">
<b>Doctor name :</b> {{item.appointment_with.user.firstname}} {{item.appointment_with.user.lastname}} <b>Department : </b> {{item.appointment_with.get_department_display}} <br>
<b> Date :</b>{{item.date}} <b>Time :</b> {{item.time_start}} - {{item.time_end}}
    {% if item.app_rate == 0 %} 
    <form method="post" action="/rate/{{item.id}}/">
        {% csrf_token %}
        <input type="radio" name="rate1" id="1" value="1">1
        <input type="radio" name="rate2" id="2" value="2">2
        <input type="radio" name="rate3" id="3" value="3">3

        <button class="btn btn-lg btn-sm btn-primary" type="submit">Rate</button>
    </form>
    {% else %}
    <br>Your rate is : {{item.app_rate}}
{% endif %}
{% endif %}
{% endfor %}
</div>

</div>
    



{% endblock %}

app/templates/app/register.html
{% extends 'app/base.html'%}
{% block body %}
<style type="text/css">
.form-signin {
  width: 100%;
  max-width: 330px;
  padding: 15px;
  margin: 0 auto;
}
.form-signin .checkbox {
  font-weight: 400;
}
.form-signin .form-control {
  position: relative;
  box-sizing: border-box;
  height: auto;
  padding: 10px;
  font-size: 16px;
}
.form-signin .form-control:focus {
  z-index: 2;
}
.form-signin input[type="email"] {
  margin-bottom: -1px;
  border-bottom-right-radius: 0;
  border-bottom-left-radius: 0;
}
.form-signin input[type="password"] {
  margin-bottom: 10px;
  border-top-left-radius: 0;
  border-top-right-radius: 0;
}

</style>


<form method="post" class="form-signin">
    {% csrf_token%}
    <h1 class="h3 mb-3 font-weight-normal">Register an account</h1>
    <input type="email" name="email" id="inputEmail" class="form-control" placeholder="Email address" required autofocus>
    <input type="firstname" name="firstname" id="inputfirstname" class="form-control" placeholder="Firstname" required autofocus>    
    <input type="lastname" name="lastname" id="inputlastname" class="form-control" placeholder="Lastname" required autofocus>    
    <input type="username" name="username" id="inputUsername" class="form-control" placeholder="Username" required autofocus>
    <input type="birthday" name="birthday" id="inputbirthday" class="form-control" placeholder="Birthday" required autofocus>
    <input type="checkbox" name="is_patient" value="True" style="display:none;" checked>     
    <input type="password" name="password1" id="inputPassword" class="form-control" placeholder="Password" required>
    <input type="password" name="password2" id="inputPassword" class="form-control" placeholder="Password" required>
   
        {% for field in reg_form %}
        <p>     
            
            {% for error in field.errors %}
                <p style="color:red;">{{error}}</p>
            {% endfor %}
        </p>
        {% endfor %}
        {% if reg_form.non_field_errors %}
        <div style="color:red;">
        <p>
            {{reg_form.non_field_errors}}
        </p></div>
        {% endif %}
        <button class="btn btn-lg btn-primary btn-block" type="submit">Register</button>
   
</form>
</div>
{% endblock %}

app/templates/app/schedule.html
{% extends 'app/base.html' %}


{% block body%}
{{app_time.appointment_with}}

<style>
    h1{
        color: yellow;
        text-align:center;
    }
    body{
    background-image: url("https://www.esmsolutions.com/wp-content/uploads/2018/02/appointment-background.jpg");
    }
    b{
        color:white;
    }
</style>
<h1>Available Dates</h1><br>
{% for item in app_time%}
<center><b>{{item.date}} | {{item.time_start}} - {{item.time_end}}</b><button><a href="/appointment/{{item.id}}/">Book</a></button><br></center>
{% endfor %}
{% endblock %}

app/templates/app/whoarewe.html
{% extends 'app/base.html' %}
{% block body%}
{% for item in data%}
{% endfor %}
<style>
    h1{
        color:Maroon;
    }
    p{
      color: Black;
      font-size: 26px;
      text-align: center;
      margin: 15px;
    }
    body{
    background-image: url("https://image.freepik.com/free-photo/blur-hospital_1203-7972.jpg");
    }
</style>
<center><h1>Hospital Appointment System</h1></center><br><br>
<p>Our goal is to make appointment system easy to use and clear </p><br>
<p>You can use our site to get appointment</p><br>
<p>You can cancel your appointments whenever you like</p><br>
<p>After appointment you can rate your doctor</p>
{% endblock %}